import { motion } from "framer-motion";

export default function BeyondCode() {
  const squares=Array.from({length:64});
  return <section id="play" className="relative py-32 bg-[#0B1020] text-white overflow-hidden">
    <div className="max-w-7xl mx-auto px-6 lg:px-12 relative z-10 grid lg:grid-cols-2 gap-16 items-center">
      <div><p className="text-cyan-400 font-semibold tracking-wider mb-3">BEYOND THE IDE</p><h2 className="text-4xl md:text-6xl font-bold">Some days I debug code.<br/><span className="bg-gradient-to-r from-cyan-300 to-violet-400 bg-clip-text text-transparent">Some days I debug the board.</span></h2><p className="mt-6 text-slate-400 text-lg leading-relaxed">Chess makes me think several moves ahead. Sudoku makes me respect constraints. Both are quiet reminders that good solutions come from seeing patterns.</p><div className="mt-8 flex flex-wrap gap-3"><span className="px-5 py-3 rounded-full border border-white/10 bg-white/5">♟ Chess</span><span className="px-5 py-3 rounded-full border border-white/10 bg-white/5">▦ Sudoku</span><span className="px-5 py-3 rounded-full border border-white/10 bg-white/5">⌘ Building</span></div></div>
      <motion.div whileHover={{scale:1.02,rotate:.4}} className="rounded-[28px] border border-white/10 bg-white/5 p-5 backdrop-blur-md"><div className="flex justify-between text-[10px] uppercase tracking-[.18em] text-slate-500 mb-4 font-mono"><span>APARNA&apos;S BOARD</span><span>THINK / TEST / MOVE</span></div><div className="grid grid-cols-8 overflow-hidden rounded-2xl">{squares.map((_,i)=><div key={i} className={((Math.floor(i/8)+i)%2===0)?"aspect-square bg-slate-200/90 grid place-items-center text-slate-900":"aspect-square bg-slate-700 grid place-items-center text-white"}>{i===2?"♞":i===13?"♟":i===58?"♘":i===52?"♙":""}</div>)}</div><div className="grid grid-cols-9 gap-0 mt-5 opacity-60">{Array.from({length:81}).map((_,i)=><span key={i} className="aspect-square border border-white/10 text-[9px] grid place-items-center text-slate-500">{((i*5+2)%9)+1}</span>)}</div></motion.div>
    </div>
  </section>;
}