import { motion } from "framer-motion";
import { FaGithub, FaExternalLinkAlt } from "react-icons/fa";
const projects=[
{title:"AI Business Assistant",type:"AI PRODUCT",desc:"An AI-powered business assistant designed around analysis, structured outputs and practical workflow automation.",tech:["LLM","AI Agents","Node.js","APIs"],github:"https://github.com/aparna8683/ai-business-assistant-",live:null},
{title:"Solron AI",type:"AI SYSTEM · IN PROGRESS",desc:"A website-analysis and AI generation workflow with validation and repair. The next milestone is public deployment.",tech:["Groq","Playwright","Node.js","GenAI"],github:"https://github.com/aparna8683/Soul_Clone_AI",live:null},
{title:"AI Resume Builder",type:"DEPLOYED",desc:"An AI-assisted resume builder with templates, themes, visibility controls, media support and PDF export.",tech:["React","Node.js","MongoDB","AI"],github:"https://github.com/aparna8683/resume_builder",live:"https://resume-builder-client-hspy.onrender.com/"},
{title:"FinTrack",type:"DEPLOYED",desc:"A personal finance application for tracking expenses and presenting financial information through a clean web interface.",tech:["React","Node.js","MongoDB"],github:"https://github.com/aparna8683/FinTrack",live:"https://fin-track-indol-xi.vercel.app/login"},
{title:"AI Interview Prep Bot",type:"DEPLOYED",desc:"An interview-practice platform built around AI-assisted mock sessions and preparation workflows.",tech:["React","Node.js","MongoDB","AI"],github:"https://github.com/aparna8683/GUVII_PROJECT",live:"https://guvii-project-frontendd.onrender.com/"},
{title:"Aivoa QMS",type:"ENGINEERING",desc:"Quality-management workflow work combining frontend, APIs, PostgreSQL and Docker.",tech:["React","FastAPI","Postgres","Docker"],github:"https://github.com/aparna8683/Aivoa-QMS",live:null}];
export default function Projects(){return <section id="projects" className="relative py-32 bg-[#080808] text-white border-t border-white/[.06]"><div className="max-w-7xl mx-auto px-6 lg:px-12"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8 mb-14"><div><p className="section-kicker">02 / SELECTED WORK</p><h2 className="display-title">Built, shipped,<br/><em>still evolving.</em></h2></div><p className="text-neutral-600 max-w-sm text-sm leading-7">A mix of deployed products and active engineering work. No inflated case studies — just what I actually built.</p></div><div className="grid md:grid-cols-2 gap-px bg-white/[.08] border border-white/[.08]">{projects.map((p,i)=><motion.article key={p.title} initial={{opacity:0}} whileInView={{opacity:1}} transition={{delay:i*.05}} viewport={{once:true}} className="bg-[#0b0b0b] p-7 md:p-9 min-h-[330px] flex flex-col hover:bg-[#101010] transition-colors"><div className="flex justify-between gap-4"><span className="text-[10px] font-medium text-neutral-600">0{i+1}</span><span className="text-[10px] font-medium text-neutral-500">{p.type}</span></div><h3 className="mt-12 text-2xl font-semibold tracking-[-.025em]">{p.title}</h3><p className="mt-4 text-sm text-neutral-500 leading-7 max-w-xl">{p.desc}</p><div className="mt-6 flex flex-wrap gap-2">{p.tech.map(t=><span key={t} className="px-2.5 py-1 border border-white/[.08] text-[10px] text-neutral-600">{t}</span>)}</div><div className="mt-auto pt-8 flex gap-5 text-xs font-medium">{p.live?<a href={p.live} target="_blank" rel="noreferrer" className="text-white flex items-center gap-2 hover:text-neutral-300"><FaExternalLinkAlt/> Demo ↗</a>:<span className="text-neutral-700">Demo · coming soon</span>}{p.github?<a href={p.github} target="_blank" rel="noreferrer" className="text-neutral-300 hover:text-white flex items-center gap-2"><FaGithub/> GitHub ↗</a>:null}</div></motion.article>)}</div><div className="mt-10 border-y border-white/[.06] py-5 flex flex-wrap gap-x-8 gap-y-3 items-center text-xs"><span className="text-neutral-600">NEXT</span><strong>House Price Prediction</strong><span className="text-neutral-600">ML project to be added as it becomes portfolio-ready.</span></div></div></section>}
